version: '3'

services:
  documentation:
    image: type32/documentation:latest
    ports:
      - "${SITE_PORT}:3000"
    restart: on-failure
    environment:
      - "NUXT_PUBLIC_SITE_URL=https://docs.crtl-prototype-studios.cn"
